


INSERT INTO TB_TAREFA (ID_TAREFA, NOME, DESCRICAO, STATUS) VALUES (TAREFA_SEQ.NEXTVAL, 'Criar API RESTful', 'desespero', 1);
INSERT INTO TB_TAREFA (ID_TAREFA, NOME, DESCRICAO, STATUS) VALUES (TAREFA_SEQ.NEXTVAL, 'Claudio Silva', 'csilva@fiap.com.br', 0);
